
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Download, Share2, RefreshCw, X, ZoomIn, ZoomOut, Maximize, Move, RotateCcw, Check } from 'lucide-react';
import { TRANSLATIONS } from '../services/translations';
import { Language } from '../types';

interface ImageModalProps {
  imageUrl: string;
  prompt?: string;
  onClose: () => void;
  onRecreate: (prompt: string) => void;
  language: Language;
}

export const ImageModal: React.FC<ImageModalProps> = ({ imageUrl, prompt, onClose, onRecreate, language }) => {
  const t = TRANSLATIONS[language === 'auto' ? 'en' : language] || TRANSLATIONS['en'];
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);
  
  const dragStartRef = useRef<{ x: number; y: number } | null>(null);
  const imageRef = useRef<HTMLImageElement>(null);

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = `eduassist-generated-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (isSharing) return;
    setIsSharing(true);
    
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();

      // 1. Try Web Share API (Mobile/Modern Browsers)
      if (navigator.share) {
        const file = new File([blob], 'eduassist-art.png', { type: 'image/png' });
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({
            files: [file],
            title: 'EduAssist AI Art',
            text: prompt || 'Check out this image generated by EduAssist AI!',
          });
          setIsSharing(false);
          return;
        }
      }

      // 2. Fallback: Copy to Clipboard (Desktop/Other Browsers)
      if (navigator.clipboard && window.ClipboardItem) {
        const data = [new ClipboardItem({ [blob.type]: blob })];
        await navigator.clipboard.write(data);
        
        setShareSuccess(true);
        setTimeout(() => setShareSuccess(false), 2000);
      } else {
        // 3. Ultimate Fallback: Just tell them to right-click
        alert("Sharing not supported. You can right-click the image to save or copy it.");
      }
    } catch (error) {
      console.error("Error sharing:", error);
    } finally {
      setIsSharing(false);
    }
  };

  const handleZoomIn = useCallback(() => {
    setZoom(prev => Math.min(prev + 0.5, 5));
  }, []);

  const handleZoomOut = useCallback(() => {
    setZoom(prev => {
      const newZoom = Math.max(prev - 0.5, 1);
      if (newZoom === 1) setPan({ x: 0, y: 0 });
      return newZoom;
    });
  }, []);

  const handleResetZoom = useCallback(() => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }, []);

  // Keyboard controls
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === '=' || e.key === '+') handleZoomIn();
      if (e.key === '-' || e.key === '_') handleZoomOut();
      if (e.key === '0') handleResetZoom();
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleZoomIn, handleZoomOut, handleResetZoom, onClose]);

  const handleMouseDown = (e: React.MouseEvent | React.TouchEvent) => {
    if (zoom > 1) {
      setIsDragging(true);
      const clientX = 'touches' in e ? e.touches[0].clientX : (e as React.MouseEvent).clientX;
      const clientY = 'touches' in e ? e.touches[0].clientY : (e as React.MouseEvent).clientY;
      dragStartRef.current = { x: clientX - pan.x, y: clientY - pan.y };
    }
  };

  const handleMouseMove = (e: React.MouseEvent | React.TouchEvent) => {
    if (isDragging && dragStartRef.current) {
      const clientX = 'touches' in e ? e.touches[0].clientX : (e as React.MouseEvent).clientX;
      const clientY = 'touches' in e ? e.touches[0].clientY : (e as React.MouseEvent).clientY;
      setPan({
        x: clientX - dragStartRef.current.x,
        y: clientY - dragStartRef.current.y
      });
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
    dragStartRef.current = null;
  };

  useEffect(() => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }, [imageUrl]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/95 backdrop-blur-2xl animate-in fade-in duration-300">
      <div className="relative w-full max-w-5xl h-full flex flex-col items-center">
        
        {/* Top Control Bar */}
        <div className="flex items-center gap-2 sm:gap-4 bg-white/10 backdrop-blur-md rounded-full px-5 py-3 mt-4 mb-6 shadow-2xl border border-white/20 z-10 animate-in slide-in-from-top-4">
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-1.5 text-white hover:text-indigo-300 transition-all rounded-full hover:bg-white/10 text-xs font-bold active:scale-95"
            title="Download"
          >
            <Download size={18} /> <span className="hidden sm:inline">{t.download}</span>
          </button>
          
          <button 
            onClick={handleShare}
            disabled={isSharing}
            className={`flex items-center gap-2 px-3 py-1.5 transition-all rounded-full hover:bg-white/10 text-xs font-bold active:scale-95 ${shareSuccess ? 'text-green-400' : 'text-white hover:text-indigo-300'}`}
            title="Share or Copy"
          >
            {shareSuccess ? <Check size={18} /> : isSharing ? <RefreshCw size={18} className="animate-spin" /> : <Share2 size={18} />} 
            <span className="hidden sm:inline">{shareSuccess ? 'Copied!' : t.share}</span>
          </button>

          {prompt && (
            <button 
              onClick={() => {
                onRecreate(prompt);
                onClose();
              }}
              className="flex items-center gap-2 px-3 py-1.5 text-white hover:text-pink-300 transition-all rounded-full hover:bg-white/10 text-xs font-bold active:scale-95"
              title="Regenerate"
            >
              <RefreshCw size={18} /> <span className="hidden sm:inline">{t.recreate}</span>
            </button>
          )}

          <div className="w-px h-6 bg-white/20 mx-1"></div>

          <button 
            onClick={onClose}
            className="p-2 text-white hover:text-red-400 transition-all rounded-full hover:bg-white/10 active:rotate-90"
            title="Close"
          >
            <X size={22} />
          </button>
        </div>

        {/* Image Container */}
        <div 
          className={`
            relative w-full flex-1 rounded-[2.5rem] overflow-hidden shadow-inner border border-white/10 bg-black/40 flex items-center justify-center touch-none
            ${zoom > 1 ? 'cursor-grab active:cursor-grabbing' : 'cursor-default'}
          `}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          onTouchStart={handleMouseDown}
          onTouchMove={handleMouseMove}
          onTouchEnd={handleMouseUp}
        >
           <img 
            ref={imageRef}
            src={imageUrl} 
            alt={prompt || "Generated Image"} 
            className="max-w-full max-h-full object-contain select-none"
            style={{ 
              transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
              transition: isDragging ? 'none' : 'transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)'
            }}
            draggable={false}
           />
           
           {/* Floating Bottom Zoom Controls */}
           <div className="absolute bottom-8 flex items-center gap-2 px-4 py-3 bg-black/60 backdrop-blur-xl rounded-2xl border border-white/10 shadow-2xl animate-in slide-in-from-bottom-6">
              <button 
                onClick={handleZoomOut} 
                disabled={zoom <= 1} 
                className="flex items-center justify-center w-10 h-10 text-white hover:bg-white/10 rounded-xl disabled:opacity-30 transition-all active:scale-90"
                title="Zoom Out (-)"
              >
                <ZoomOut size={20} />
              </button>
              
              <div className="w-20 text-center flex flex-col items-center">
                <span className="text-[10px] font-black text-white/40 uppercase tracking-tighter mb-0.5">Zoom</span>
                <span className="text-xs font-black text-white tracking-widest leading-none">{Math.round(zoom * 100)}%</span>
              </div>
              
              <button 
                onClick={handleZoomIn} 
                disabled={zoom >= 5} 
                className="flex items-center justify-center w-10 h-10 text-white hover:bg-white/10 rounded-xl disabled:opacity-30 transition-all active:scale-90"
                title="Zoom In (+)"
              >
                <ZoomIn size={20} />
              </button>
              
              {(zoom > 1 || pan.x !== 0 || pan.y !== 0) && (
                <>
                  <div className="w-px h-6 bg-white/20 mx-1"></div>
                  <button 
                    onClick={handleResetZoom} 
                    className="flex items-center justify-center gap-2 px-4 h-10 text-white bg-indigo-500/80 hover:bg-indigo-500 rounded-xl transition-all active:scale-95 shadow-lg shadow-indigo-500/20"
                    title="Reset View (0)"
                  >
                    <RotateCcw size={16} />
                    <span className="text-[10px] font-black uppercase tracking-widest">Reset</span>
                  </button>
                </>
              )}
           </div>

           {zoom > 1 && !isDragging && (
             <div className="absolute top-6 left-1/2 -translate-x-1/2 bg-indigo-500/60 text-white text-[10px] px-5 py-2.5 rounded-full pointer-events-none backdrop-blur-md flex items-center gap-2 animate-bounce font-black tracking-widest border border-white/20 shadow-2xl">
               <Move size={14} /> DRAG TO EXPLORE
             </div>
           )}
        </div>
        
        {/* Footer Prompt Card */}
        {prompt && (
          <div className="mt-6 mb-8 glass-panel px-8 py-5 rounded-[2rem] border-white/10 max-w-2xl shadow-2xl animate-in fade-in slide-in-from-bottom-4 duration-700">
            <p className="text-white/90 text-sm text-center italic font-medium leading-relaxed">
              "{prompt}"
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
